# nglims integration requires a Galaxy server containing
# information about samples on each flowcell.
galaxy_url: http://nglims.you.org/galaxy
galaxy_apikey: apikey_from_Galaxy
# Directoryies where Illumina puts finished flowcells
dump_directories:
  - /array1
  - /array2
# Locaton of processing machine. Files will be rsync'ed using the
# provided username which assumes correct setup of passwordless ssh-keys.
# Starts a remote bcbio server for kicking off analysis.
process:
  host: workserver.you.org
  username: bcbio_user
  dir: /array1/bcbio
  server: http://workserver.you.org/bcbio
# Local cores to use for processing bcl to bgzipped fastq files
algorithm:
  num_cores: 8
# Pointer to a plain text file which will be used to keep track of 
# directories that have already been transferred.
msg_db: /opt/transfer/transferred.db
# Logging output for preparation and transfer steps
log_dir: /opt/transfer/log