# Template for mouse chip-seq using Illumina prepared samples
---
details:
- analysis: chip-seq
  genome_build: mm10
  algorithm:
    aligner: bowtie2
    adapters: [truseq]
    trim_reads: read_through
    peakcaller: [macs2]
  resources:
    macs2:
      options: ["--broad", "-q 0.05"]

