# Launch analysis environment on AWS with existing data volume.
# For bcbio analyses, volume expected to contain bcbio installation
# in /mnt/work/bcbio
# Makes it easy to stop/start analyses that fit on a single node and EBS volume.
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - include_vars: project_vars.yaml
    - name: Launch EC2 instance
      register: ec2
      local_action:
        module: ec2
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        spot_price: "{{ spot_price }}"
        image: "{{ image_id }}"
        keypair: "{{ keypair }}"
        vpc_subnet_id: "{{ vpc_subnet }}"
        instance_profile_name: "{{ iam_role }}"
        assign_public_ip: yes
        count: 1
        wait: yes
        state: present
    - name: Attach working volume
      local_action: ec2_vol instance={{ item.id }} id={{ volume }} device_name=/dev/xvdf state=present
      with_items: "{{ ec2.instances }}"
    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_dns_name }} groupname=launched
      with_items: "{{ ec2.instances }}"
    - name: Wait for SSH
      local_action: wait_for host={{ item.public_ip }} port=22 state=started
      with_items: "{{ ec2.instances }}"
    - name: Get rid of SSH "Are you sure you want to continue connecting (yes/no)?" query
      shell: ssh-keyscan {{ item.public_ip }} >> $HOME/.ssh/known_hosts
      with_items: "{{ ec2.instances }}"

- hosts: launched
  remote_user: ubuntu
  gather_facts: true
  tasks:
    - include_vars: project_vars.yaml
    - apt: name="{{ item }}" update_cache=yes
      become: true
      with_items: [git, unzip, wget, tar, gzip, bzip2]
    - name: Mount work volume
      become: true
      mount: name=/mnt/work src=/dev/xvdf fstype=ext4 state=mounted
    - name: Add bcbio to path
      lineinfile: line="export PATH=/mnt/work/bcbio/bin:$PATH" dest=~/.bashrc
